# Generated by Django 2.2.4 on 2019-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190812_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mem_weekly_added_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
