# Generated by Django 2.2.4 on 2019-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_member_mem_weekly_added_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_description_en',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_name_en',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_week_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
