# Generated by Django 2.2.4 on 2019-08-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190816_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mem_last_weekly_added_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
