# Generated by Django 2.2.4 on 2019-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190819_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_description_ar',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_five',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_four',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_one',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_three',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_two',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_five_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_five_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_four_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_four_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_one_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_one_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_three_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_three_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_two_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_two_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
